# Project Name

**Author:** First Last  
**Last modified:** mm-dd-yyyy (*created:* mm-dd-yyyy)  
  
  
**Description:** Add a short paragraph explaining the project here
  
---

#### Import libraries
* **library:** explain purpose of library here
* **pandas:** for data frames and cleaning (data wrangling)

In [1]:
import pandas as pd

---

#### Load data
* **file_name**

In [3]:
# example code to read csv file
soccer_df=pd.read_excel('C:\\Users\\namb2\\OneDrive\\Documents\\GitHub\\BAIS3140_final_project_repo\\data\\final_data\\prem_league_09_19.xlsx')

# review
soccer_df

,Match Date,Home Team,Away Team,Full Time Home Team Goals,Full Time Away Team Goals,Game Result,Half Time Home Team Goals,Half Time Away Team Goals,Half Time Result,Match Referee,...,Home Team Shots on Goal,Away Team Shots on Goal,Home Team Fouls Committed,Away Team Fouls Committed,Home Team Corners,Away Team Corners,Home Team Yellow Cards,Away Team Yellow Cards,Home Team Red Cards,Away Team Red Cards
0,15/08/09,Aston Villa,Wigan,0,2,A,0,1,A,M Clattenburg,...,5,7,15,14,4,6,2,2,0,0
1,15/08/09,Blackburn,Man City,0,2,A,0,1,A,M Dean,...,9,5,12,9,5,4,2,1,0,0
2,15/08/09,Bolton,Sunderland,0,1,A,0,1,A,A Marriner,...,3,13,16,10,4,7,2,1,0,0
3,15/08/09,Chelsea,Hull,2,1,H,1,1,D,A Wiley,...,12,3,13,15,12,4,1,2,0,0
4,15/08/09,Everton,Arsenal,1,6,A,0,3,A,M Halsey,...,5,9,11,13,4,9,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3625,02/01/19,Huddersfield,Burnley,1,2,A,1,1,D,M Dean,...,2,8,11,9,5,2,0,4,1,1
3626,02/01/19,Newcastle,Man United,0,2,A,0,0,D,A Marriner,...,3,7,10,9,1,2,1,2,0,0
3627,02/01/19,West Ham,Brighton,2,2,D,0,0,D,C Kavanagh,...,6,6,9,11,1,5,0,1,0,0
3628,02/01/19,Wolves,Crystal Palace,0,2,A,0,0,D,R East,...,1,4,9,7,3,10,4,1,0,0
3629,03/01/19,Man City,Liverpool,2,1,H,1,0,H,A Taylor,...,4,5,12,7,2,1,4,2,0,0

---

#### Transform Data to Keep Rows where Arsenal is Team and Determine whether They are Home or Away

In [7]:
# Create a DataFrame for home games with 'Opponent' column
home_df = soccer_df.rename(columns={'Home Team': 'Team', 'Away Team': 'Opponent'})
home_df['Home/Away'] = 'Home'

# Create a DataFrame for away games with 'Opponent' column
away_df = soccer_df.rename(columns={'Away Team': 'Team', 'Home Team': 'Opponent'})
away_df['Home/Away'] = 'Away'

# Combine the dataframes
melted_df = pd.concat([home_df, away_df], ignore_index=True)

# Review the result
melted_df

,Match Date,Team,Opponent,Full Time Home Team Goals,Full Time Away Team Goals,Game Result,Half Time Home Team Goals,Half Time Away Team Goals,Half Time Result,Match Referee,...,Away Team Shots on Goal,Home Team Fouls Committed,Away Team Fouls Committed,Home Team Corners,Away Team Corners,Home Team Yellow Cards,Away Team Yellow Cards,Home Team Red Cards,Away Team Red Cards,Home/Away
0,15/08/09,Aston Villa,Wigan,0,2,A,0,1,A,M Clattenburg,...,7,15,14,4,6,2,2,0,0,Home
1,15/08/09,Blackburn,Man City,0,2,A,0,1,A,M Dean,...,5,12,9,5,4,2,1,0,0,Home
2,15/08/09,Bolton,Sunderland,0,1,A,0,1,A,A Marriner,...,13,16,10,4,7,2,1,0,0,Home
3,15/08/09,Chelsea,Hull,2,1,H,1,1,D,A Wiley,...,3,13,15,12,4,1,2,0,0,Home
4,15/08/09,Everton,Arsenal,1,6,A,0,3,A,M Halsey,...,9,11,13,4,9,0,0,0,0,Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7255,02/01/19,Burnley,Huddersfield,1,2,A,1,1,D,M Dean,...,8,11,9,5,2,0,4,1,1,Away
7256,02/01/19,Man United,Newcastle,0,2,A,0,0,D,A Marriner,...,7,10,9,1,2,1,2,0,0,Away
7257,02/01/19,Brighton,West Ham,2,2,D,0,0,D,C Kavanagh,...,6,9,11,1,5,0,1,0,0,Away
7258,02/01/19,Crystal Palace,Wolves,0,2,A,0,0,D,R East,...,4,9,7,3,10,4,1,0,0,Away
7259,03/01/19,Liverpool,Man City,2,1,H,1,0,H,A Taylor,...,5,12,7,2,1,4,2,0,0,Away

In [9]:
# rename half time result to ahead, behind, tied
def calculate_half_time_result(row):
    if row['Home/Away'] == 'Home':
        if row['Half Time Home Team Goals'] > row['Half Time Away Team Goals']:
            return 'Ahead'
        elif row['Half Time Home Team Goals'] < row['Half Time Away Team Goals']:
            return 'Behind'
        elif row['Half Time Home Team Goals'] == row['Half Time Away Team Goals']:
            return 'Tied'
    elif row['Home/Away'] == 'Away':
        if row['Half Time Home Team Goals'] < row['Half Time Away Team Goals']:
            return 'Ahead'
        elif row['Half Time Home Team Goals'] > row['Half Time Away Team Goals']:
            return 'Behind'
        elif row['Half Time Home Team Goals'] == row['Half Time Away Team Goals']:
            return 'Tied'

melted_df['Half Time Result']=melted_df.apply(calculate_half_time_result, axis=1)

melted_df

,Match Date,Team,Opponent,Full Time Home Team Goals,Full Time Away Team Goals,Game Result,Half Time Home Team Goals,Half Time Away Team Goals,Half Time Result,Match Referee,...,Away Team Shots on Goal,Home Team Fouls Committed,Away Team Fouls Committed,Home Team Corners,Away Team Corners,Home Team Yellow Cards,Away Team Yellow Cards,Home Team Red Cards,Away Team Red Cards,Home/Away
0,15/08/09,Aston Villa,Wigan,0,2,A,0,1,Behind,M Clattenburg,...,7,15,14,4,6,2,2,0,0,Home
1,15/08/09,Blackburn,Man City,0,2,A,0,1,Behind,M Dean,...,5,12,9,5,4,2,1,0,0,Home
2,15/08/09,Bolton,Sunderland,0,1,A,0,1,Behind,A Marriner,...,13,16,10,4,7,2,1,0,0,Home
3,15/08/09,Chelsea,Hull,2,1,H,1,1,Tied,A Wiley,...,3,13,15,12,4,1,2,0,0,Home
4,15/08/09,Everton,Arsenal,1,6,A,0,3,Behind,M Halsey,...,9,11,13,4,9,0,0,0,0,Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7255,02/01/19,Burnley,Huddersfield,1,2,A,1,1,Tied,M Dean,...,8,11,9,5,2,0,4,1,1,Away
7256,02/01/19,Man United,Newcastle,0,2,A,0,0,Tied,A Marriner,...,7,10,9,1,2,1,2,0,0,Away
7257,02/01/19,Brighton,West Ham,2,2,D,0,0,Tied,C Kavanagh,...,6,9,11,1,5,0,1,0,0,Away
7258,02/01/19,Crystal Palace,Wolves,0,2,A,0,0,Tied,R East,...,4,9,7,3,10,4,1,0,0,Away
7259,03/01/19,Liverpool,Man City,2,1,H,1,0,Behind,A Taylor,...,5,12,7,2,1,4,2,0,0,Away

In [11]:
# do the same for the match result
def calculate_half_time_result(row):
    if row['Home/Away'] == 'Home':
        if row['Full Time Home Team Goals'] > row['Full Time Away Team Goals']:
            return 'Win'
        elif row['Full Time Home Team Goals'] < row['Full Time Away Team Goals']:
            return 'Loss'
        elif row['Full Time Home Team Goals'] == row['Full Time Away Team Goals']:
            return 'Draw'
    elif row['Home/Away'] == 'Away':
        if row['Full Time Home Team Goals'] < row['Full Time Away Team Goals']:
            return 'Win'
        elif row['Full Time Home Team Goals'] > row['Full Time Away Team Goals']:
            return 'Loss'
        elif row['Full Time Home Team Goals'] == row['Full Time Away Team Goals']:
            return 'Draw'

melted_df['Game Result']=melted_df.apply(calculate_half_time_result, axis=1)

melted_df

,Match Date,Team,Opponent,Full Time Home Team Goals,Full Time Away Team Goals,Game Result,Half Time Home Team Goals,Half Time Away Team Goals,Half Time Result,Match Referee,...,Away Team Shots on Goal,Home Team Fouls Committed,Away Team Fouls Committed,Home Team Corners,Away Team Corners,Home Team Yellow Cards,Away Team Yellow Cards,Home Team Red Cards,Away Team Red Cards,Home/Away
0,15/08/09,Aston Villa,Wigan,0,2,Loss,0,1,Behind,M Clattenburg,...,7,15,14,4,6,2,2,0,0,Home
1,15/08/09,Blackburn,Man City,0,2,Loss,0,1,Behind,M Dean,...,5,12,9,5,4,2,1,0,0,Home
2,15/08/09,Bolton,Sunderland,0,1,Loss,0,1,Behind,A Marriner,...,13,16,10,4,7,2,1,0,0,Home
3,15/08/09,Chelsea,Hull,2,1,Win,1,1,Tied,A Wiley,...,3,13,15,12,4,1,2,0,0,Home
4,15/08/09,Everton,Arsenal,1,6,Loss,0,3,Behind,M Halsey,...,9,11,13,4,9,0,0,0,0,Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7255,02/01/19,Burnley,Huddersfield,1,2,Win,1,1,Tied,M Dean,...,8,11,9,5,2,0,4,1,1,Away
7256,02/01/19,Man United,Newcastle,0,2,Win,0,0,Tied,A Marriner,...,7,10,9,1,2,1,2,0,0,Away
7257,02/01/19,Brighton,West Ham,2,2,Draw,0,0,Tied,C Kavanagh,...,6,9,11,1,5,0,1,0,0,Away
7258,02/01/19,Crystal Palace,Wolves,0,2,Win,0,0,Tied,R East,...,4,9,7,3,10,4,1,0,0,Away
7259,03/01/19,Liverpool,Man City,2,1,Loss,1,0,Behind,A Taylor,...,5,12,7,2,1,4,2,0,0,Away

In [13]:
cols=melted_df.columns
for col in cols:
    print(f'\'{col}\',')

'Match Date',
'Team',
'Opponent',
'Full Time Home Team Goals',
'Full Time Away Team Goals',
'Game Result',
'Half Time Home Team Goals',
'Half Time Away Team Goals',
'Half Time Result',
'Match Referee',
'Home Team Shots',
'Away Team Shots',
'Home Team Shots on Goal',
'Away Team Shots on Goal',
'Home Team Fouls Committed',
'Away Team Fouls Committed',
'Home Team Corners',
'Away Team Corners',
'Home Team Yellow Cards',
'Away Team Yellow Cards',
'Home Team Red Cards',
'Away Team Red Cards',
'Home/Away',

In [15]:
# convert columns

melted_df['Total Goals For']=melted_df.apply(
    lambda row: row['Full Time Home Team Goals'] if row['Home/Away'] == 'Home' else row['Full Time Away Team Goals'],axis=1)

melted_df['Total Goals Against']=melted_df.apply(
    lambda row: row['Full Time Away Team Goals'] if row['Home/Away'] == 'Home' else row['Full Time Home Team Goals'],axis=1)

melted_df['Half Time Goals For']=melted_df.apply(
    lambda row: row['Half Time Home Team Goals'] if row['Home/Away'] == 'Home' else row['Half Time Away Team Goals'],axis=1)

melted_df['Half Time Goals Against']=melted_df.apply(
    lambda row: row['Half Time Away Team Goals'] if row['Home/Away'] == 'Home' else row['Half Time Home Team Goals'],axis=1)

melted_df['Shots For']=melted_df.apply(
    lambda row: row['Home Team Shots'] if row['Home/Away'] == 'Home' else row['Away Team Shots'],axis=1)

melted_df['Shots Against']=melted_df.apply(
    lambda row: row['Away Team Shots'] if row['Home/Away'] == 'Home' else row['Home Team Shots'],axis=1)

melted_df['Shots For On Goal']=melted_df.apply(
    lambda row: row['Home Team Shots on Goal'] if row['Home/Away'] == 'Home' else row['Away Team Shots on Goal'],axis=1)

melted_df['Shots Against On Goal']=melted_df.apply(
    lambda row: row['Away Team Shots on Goal'] if row['Home/Away'] == 'Home' else row['Home Team Shots on Goal'],axis=1)

melted_df['Corners For']=melted_df.apply(
    lambda row: row['Home Team Corners'] if row['Home/Away'] == 'Home' else row['Away Team Corners'],axis=1)

melted_df['Corners Against']=melted_df.apply(
    lambda row: row['Away Team Corners'] if row['Home/Away'] == 'Home' else row['Home Team Corners'],axis=1)

melted_df['Yellow Cards']=melted_df.apply(
    lambda row: row['Home Team Yellow Cards'] if row['Home/Away'] == 'Home' else row['Away Team Yellow Cards'],axis=1)

melted_df['Oppenent Yellow Cards']=melted_df.apply(
    lambda row: row['Away Team Yellow Cards'] if row['Home/Away'] == 'Home' else row['Home Team Yellow Cards'],axis=1)

melted_df['Fouls Committed']=melted_df.apply(
    lambda row: row['Home Team Fouls Committed'] if row['Home/Away'] == 'Home' else row['Away Team Fouls Committed'],axis=1)

melted_df['Oppenent Fouls Committed']=melted_df.apply(
    lambda row: row['Away Team Fouls Committed'] if row['Home/Away'] == 'Home' else row['Home Team Fouls Committed'],axis=1)

melted_df['Red Cards']=melted_df.apply(
    lambda row: row['Home Team Red Cards'] if row['Home/Away'] == 'Home' else row['Away Team Red Cards'],axis=1)

melted_df['Oppenent Red Cards']=melted_df.apply(
    lambda row: row['Away Team Red Cards'] if row['Home/Away'] == 'Home' else row['Home Team Red Cards'],axis=1)

cols_to_drop=['Full Time Home Team Goals','Full Time Away Team Goals','Half Time Home Team Goals','Half Time Away Team Goals',
              'Half Time Result','Home Team Shots','Away Team Shots','Home Team Shots on Goal','Away Team Shots on Goal',
              'Home Team Fouls Committed','Away Team Fouls Committed','Home Team Corners','Away Team Corners',
              'Home Team Yellow Cards','Away Team Yellow Cards','Home Team Red Cards','Away Team Red Cards']

melted_df=melted_df.drop(columns=cols_to_drop)

melted_df.head()

,Match Date,Team,Opponent,Game Result,Match Referee,Home/Away,Total Goals For,Total Goals Against,Half Time Goals For,Half Time Goals Against,...,Shots For On Goal,Shots Against On Goal,Corners For,Corners Against,Yellow Cards,Oppenent Yellow Cards,Fouls Committed,Oppenent Fouls Committed,Red Cards,Oppenent Red Cards
0,15/08/09,Aston Villa,Wigan,Loss,M Clattenburg,Home,0,2,0,1,...,5,7,4,6,2,2,15,14,0,0
1,15/08/09,Blackburn,Man City,Loss,M Dean,Home,0,2,0,1,...,9,5,5,4,2,1,12,9,0,0
2,15/08/09,Bolton,Sunderland,Loss,A Marriner,Home,0,1,0,1,...,3,13,4,7,2,1,16,10,0,0
3,15/08/09,Chelsea,Hull,Win,A Wiley,Home,2,1,1,1,...,12,3,12,4,1,2,13,15,0,0
4,15/08/09,Everton,Arsenal,Loss,M Halsey,Home,1,6,0,3,...,5,9,4,9,0,0,11,13,0,0

In [16]:
# Convert 'Match Date' to datetime 
melted_df['Match Date'] = pd.to_datetime(melted_df['Match Date'], format='%d/%m/%y') 
# Filter out rows where the year is 2019 
melted_df = melted_df[melted_df['Match Date'].dt.year != 2019]

melted_df.head()

,Match Date,Team,Opponent,Game Result,Match Referee,Home/Away,Total Goals For,Total Goals Against,Half Time Goals For,Half Time Goals Against,...,Shots For On Goal,Shots Against On Goal,Corners For,Corners Against,Yellow Cards,Oppenent Yellow Cards,Fouls Committed,Oppenent Fouls Committed,Red Cards,Oppenent Red Cards
0,2009-08-15,Aston Villa,Wigan,Loss,M Clattenburg,Home,0,2,0,1,...,5,7,4,6,2,2,15,14,0,0
1,2009-08-15,Blackburn,Man City,Loss,M Dean,Home,0,2,0,1,...,9,5,5,4,2,1,12,9,0,0
2,2009-08-15,Bolton,Sunderland,Loss,A Marriner,Home,0,1,0,1,...,3,13,4,7,2,1,16,10,0,0
3,2009-08-15,Chelsea,Hull,Win,A Wiley,Home,2,1,1,1,...,12,3,12,4,1,2,13,15,0,0
4,2009-08-15,Everton,Arsenal,Loss,M Halsey,Home,1,6,0,3,...,5,9,4,9,0,0,11,13,0,0

---
#### Save data
* **file_name** (to be saved to)

In [20]:
# export
melted_df.to_excel('C:\\Users\\namb2\\OneDrive\\Documents\\GitHub\\BAIS3140_final_project_repo\\data\\final_data\\prem_league_cleaned.xlsx',index=True)